/*  
# Description: CUSTOMER_INVOICE FINAL VIEW  LOAD
# Created by: NANDAKUMAR PANDIAN
# Created on: 19/12/2016
# Revision History :
# Latest Modification History on top

# DD/MM/YYYY Who(Network id) Version Modification Details
# 19/12/2016        NANDAKUMAR PANDIAN      01         CUSTOMER_INVOICE FINAL VIEW  LOAD
*/

DROP VIEW  IF  EXISTS CUSTOMER_CORE.CUSTOMER_FINAL_VIEW;

CREATE VIEW  IF NOT EXISTS CUSTOMER_CORE.CUSTOMER_FINAL_VIEW
AS
SELECT 
A.CUSTOMER_ID,A.CUSTOMER_FIRST_NAME,A.PRODUCT_TITLE,A.PRODUCT_QTY,A.DERIVED_PRD_COST,A.DERIVED_VAT_PYBL,A.DERIVED_TOT_COST,B.ACCOUNT_NM,B.OEDER_ID AS ORDER_ID,B.CUSTOMER_MIDDLE_NAME,
B.CUSTOMER_LAST_NAME,B.GENDER,B.EMAIL_ADDRESS,B.PHONE_NUM,B.PRODUCT_NAME,B.PRODUCT_PRICE,B.PRODUCT_COLOR,B.PRODUCT_SIZE,B.ADDRESS_LINE_1,B.ADDRESS_LINE_2,B.ADDRESS_LINE_3,
B.ADDRESS_LINE_4,B.TOWN_CITY,B.STATE,B.COUNTRY,B.COUNTRY_CODE,C.MODE_OF_SHIPPING,C.COURIER_NM,D.SUPPLIED_BY,D.SUPPLIED_ITEMS,D.SUPPLIED_DT_TIME,D.SUPPLIER_STATUS,E.TRANS_AMOUNT,
E.TRANS_TYP_CD,E.TRANS_TYP_DESC,F.SUPPLIER_ID,F.PRODUCT_TYPE_CD,F.PARENT_PRD_TYP_CD,F.PRD_TYP_DESC,F.VAT_RATING,A.START_DATE,A.END_DATE
FROM CUSTOMER_CORE.CUSTOMER_PRODUCT_DTLS B 
INNER JOIN CUSTOMER_CORE.CUSTOMER_SHIPPINGT_DTLS C 
ON B.CUSTOMER_ID=C.CUSTOMER_ID
LEFT OUTER JOIN CUSTOMER_CORE.CUSTOMER_INVOICE_ITEM_DTLS A
ON B.CUSTOMER_ID=A.CUSTOMER_ID
LEFT OUTER JOIN CUSTOMER_CORE.CUSTOMER_SUP_DTLS D
ON B.CUSTOMER_ID=D.CUSTOMER_ID
LEFT OUTER JOIN CUSTOMER_CORE.CUSTOMER_TRANS_DTLS E
ON B.CUSTOMER_ID=E.CUSTOMER_ID
LEFT OUTER JOIN CUSTOMER_CORE.SUPPLIER_PROD_TYP_DTLS F
ON D.SUPPLIED_ITEMS=F.SUPPLIED_ITEMS
LEFT OUTER JOIN CUSTOMER_CORE.SUPPLIER_SHIPPING_DTLS G
ON F.SUPPLIED_ITEMS=G.SUPPLIED_ITEMS;