/*  
# Description: CUSTOMER_INVOICE CORE TABLES LOAD
# Created by: NANDAKUMAR PANDIAN
# Created on: 19/12/2016
# Revision History :
# Latest Modification History on top

# DD/MM/YYYY Who(Network id) Version Modification Details
# 19/12/2016        NANDAKUMAR PANDIAN      01         CUSTOMER_INVOICE CORE TABLES LOAD
*/


------Customer Core Table coding
SET hive.exec.dynamic.partition.mode=nonstrict;

---TABLE-1 CUSTOMER_PRODUCT_DTLS

DROP TABLE CUSTOMER_CORE.CUSTOMER_PRODUCT_DTLS;

CREATE TABLE  IF NOT EXISTS CUSTOMER_CORE.CUSTOMER_PRODUCT_DTLS (
CUSTOMER_ID INT,ACCOUNT_NM INT,OEDER_ID INT,CUSTOMER_FIRST_NAME STRING,CUSTOMER_MIDDLE_NAME STRING,CUSTOMER_LAST_NAME STRING,
GENDER CHAR(6),EMAIL_ADDRESS STRING,PHONE_NUM INT,PRODUCT_NAME STRING,PRODUCT_PRICE FLOAT,PRODUCT_COLOR STRING,PRODUCT_SIZE CHAR(4),
ADDRESS_LINE_1 STRING,ADDRESS_LINE_2 STRING,ADDRESS_LINE_3 STRING,ADDRESS_LINE_4 STRING,TOWN_CITY STRING,STATE STRING,COUNTRY STRING,
COUNTRY_CODE CHAR(3),START_DATE DATE, END_DATE DATE   )
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS ORC;

INSERT OVERWRITE TABLE CUSTOMER_CORE.CUSTOMER_PRODUCT_DTLS
SELECT  CUSTOMER.CUSTOMER_ID ,ACCOUNT.ACC_NM ,ORDERS.ORDER_ID ,CUSTOMER.CUSTOMER_FIRST_NAME ,CUSTOMER.CUSTOMER_MIDDLE_NAME ,CUSTOMER.CUSTOMER_LAST_NAME ,
CUSTOMER.GENDER ,CUSTOMER.EMAIL_ADDRESS ,CUSTOMER.PHONE_NUM ,PRODUCTS.PRODUCT_NAME ,
SUM(PRODUCTS.PRODUCT_PRICE) AS PRODUCT_PRICE,
PRODUCTS.PRODUCT_COLOR ,PRODUCTS.PRODUCT_SIZE ,CUSTOMER.ADDRESS_LINE_1 ,CUSTOMER.ADDRESS_LINE_2 ,
CUSTOMER.ADDRESS_LINE_3 ,CUSTOMER.ADDRESS_LINE_4 ,CUSTOMER.TOWN_CITY ,CUSTOMER.STATE ,CUSTOMER.COUNTRY ,
CUSTOMER.COUNTRY_CODE ,CUSTOMER.START_DATE ,CUSTOMER.END_DATE 
FROM CUSTOMER_STG.CUSTOMER CUSTOMER
INNER JOIN CUSTOMER_STG.ACCOUNT ACCOUNT
ON CUSTOMER.CUSTOMER_ID=ACCOUNT.CUSTOMER_ID
INNER JOIN CUSTOMER_STG.ORDER ORDERS
ON CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID
LEFT OUTER JOIN CUSTOMER_STG.ORDER_ITEM ORDERS_ITEMS
ON ORDERS.ORDER_ID=ORDERS_ITEMS.ORDER_ID
LEFT OUTER JOIN CUSTOMER_STG.PRODUCT PRODUCTS
ON PRODUCTS.PRODUCT_ID=ORDERS_ITEMS.PRODUCT_ID
GROUP BY  CUSTOMER.CUSTOMER_ID,ACCOUNT.ACC_NM ,ORDERS.ORDER_ID ,CUSTOMER.CUSTOMER_FIRST_NAME ,CUSTOMER.CUSTOMER_MIDDLE_NAME ,
CUSTOMER.CUSTOMER_LAST_NAME ,CUSTOMER.GENDER ,CUSTOMER.EMAIL_ADDRESS ,CUSTOMER.PHONE_NUM ,PRODUCTS.PRODUCT_NAME ,
PRODUCTS.PRODUCT_COLOR ,PRODUCTS.PRODUCT_SIZE ,CUSTOMER.ADDRESS_LINE_1 ,CUSTOMER.ADDRESS_LINE_2 ,CUSTOMER.ADDRESS_LINE_3 ,
CUSTOMER.ADDRESS_LINE_4 ,CUSTOMER.TOWN_CITY ,CUSTOMER.STATE ,CUSTOMER.COUNTRY ,CUSTOMER.COUNTRY_CODE ,CUSTOMER.START_DATE ,CUSTOMER.END_DATE;

---TABLE-2 CUSTOMER_SHIPPINGT_DTLS

DROP TABLE  IF  EXISTS CUSTOMER_CORE.CUSTOMER_SHIPPINGT_DTLS;

CREATE TABLE  IF NOT EXISTS CUSTOMER_CORE.CUSTOMER_SHIPPINGT_DTLS (
CUSTOMER_ID INT,CUSTOMER_FIRST_NAME STRING,GENDER CHAR(6),EMAIL_ADDRESS STRING,PHONE_NUM INT,
MODE_OF_SHIPPING STRING,COURIER_NM STRING,START_DATE DATE, END_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS ORC;

INSERT OVERWRITE TABLE CUSTOMER_CORE.CUSTOMER_SHIPPINGT_DTLS  
SELECT  CUSTOMER.CUSTOMER_ID ,CUSTOMER.CUSTOMER_FIRST_NAME ,CUSTOMER.GENDER ,CUSTOMER.EMAIL_ADDRESS ,CUSTOMER.PHONE_NUM , SHIPPING.MODE_OF_SHIPPING,SHIPPING.COURIER_NM ,
CUSTOMER.START_DATE ,CUSTOMER.END_DATE 
FROM CUSTOMER_STG.CUSTOMER CUSTOMER
INNER JOIN CUSTOMER_STG.ACCOUNT ACCOUNT
ON CUSTOMER.CUSTOMER_ID=ACCOUNT.CUSTOMER_ID
INNER JOIN CUSTOMER_STG.ORDER ORDERS
ON CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID
LEFT OUTER JOIN CUSTOMER_STG.ORDER_ITEM ORDERS_ITEMS
ON ORDERS.ORDER_ID=ORDERS_ITEMS.ORDER_ID
LEFT OUTER JOIN CUSTOMER_STG.PRODUCT PRODUCTS
ON PRODUCTS.PRODUCT_ID=ORDERS_ITEMS.PRODUCT_ID
LEFT OUTER JOIN CUSTOMER_STG.INVOICE_LINE_ITEMS INVOICE_ITEM
ON PRODUCTS.PRODUCT_ID=INVOICE_ITEM.PRODUCT_ID
LEFT OUTER JOIN CUSTOMER_STG.SHIPPING_DETAIL SHIPPING
ON INVOICE_ITEM.SHIPPING_ID=SHIPPING.SHIPPING_ID ;

---TABLE-3  CUSTOMER_TRANS_DTLS

DROP TABLE  IF  EXISTS CUSTOMER_CORE.CUSTOMER_TRANS_DTLS;

CREATE TABLE  IF NOT EXISTS CUSTOMER_CORE.CUSTOMER_TRANS_DTLS (
CUSTOMER_ID INT,CUSTOMER_FIRST_NAME STRING,TRANS_AMOUNT FLOAT,TRANS_TYP_CD CHAR(4),TRANS_TYP_DESC STRING,
START_DATE DATE, END_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS ORC;

INSERT OVERWRITE TABLE CUSTOMER_CORE.CUSTOMER_TRANS_DTLS  
SELECT  CUSTOMER.CUSTOMER_ID ,CUSTOMER.CUSTOMER_FIRST_NAME ,
FINANCIAL_TXN.TRANS_AMT,FINANCIAL_TXN.TRANS_TYP_CD,TRANSACTION_TYPE.TRANS_TYP_DESC,
CUSTOMER.START_DATE ,CUSTOMER.END_DATE 
FROM CUSTOMER_STG.CUSTOMER CUSTOMER
INNER JOIN CUSTOMER_STG.ACCOUNT ACCOUNT
ON CUSTOMER.CUSTOMER_ID=ACCOUNT.CUSTOMER_ID
INNER JOIN CUSTOMER_STG.ORDER ORDERS
ON CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID
LEFT OUTER JOIN CUSTOMER_STG.INVOICE INVOICE
ON ORDERS.ORDER_ID=INVOICE.ORDER_ID
LEFT OUTER JOIN CUSTOMER_STG.FINANCIAL_TXN FINANCIAL_TXN
ON INVOICE.INVOICE_NUM=FINANCIAL_TXN.INVOICE_NUM
LEFT OUTER JOIN CUSTOMER_STG.TRANSACTION_TYPE TRANSACTION_TYPE
ON FINANCIAL_TXN.TRANS_TYP_CD=TRANSACTION_TYPE.TRANS_TYP_CD ;


---TABLE-4  CUSTOMER_SUP_DTLS

DROP TABLE  IF  EXISTS CUSTOMER_CORE.CUSTOMER_SUP_DTLS;

CREATE TABLE  IF NOT EXISTS CUSTOMER_CORE.CUSTOMER_SUP_DTLS (
CUSTOMER_ID INT,CUSTOMER_FIRST_NAME STRING,
SUPPLIED_BY STRING,SUPPLIED_ITEMS STRING ,SUPPLIED_DT_TIME TIMESTAMP,SUPPLIER_STATUS CHAR(1),
START_DATE DATE, END_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS ORC;

INSERT OVERWRITE TABLE CUSTOMER_CORE.CUSTOMER_SUP_DTLS  
SELECT  CUSTOMER.CUSTOMER_ID ,CUSTOMER.CUSTOMER_FIRST_NAME ,
SUPPLIER.SUPPLIED_BY  ,SUPPLIER.SUPPLIED_ITEMS  ,SUPPLIER.SUPPLIED_DT_TIME,SUPPLIER.SUPPLIER_STATUS,
CUSTOMER.START_DATE ,CUSTOMER.END_DATE 
FROM CUSTOMER_STG.CUSTOMER CUSTOMER
INNER JOIN CUSTOMER_STG.DELIVERY_DETAIL DELIVERY
ON CUSTOMER.CUSTOMER_ID=DELIVERY.CUSTOMER_ID
LEFT OUTER JOIN  CUSTOMER_STG.PRODUCT PRODUCT
ON DELIVERY.PRODUCT_ID=PRODUCT.PRODUCT_ID
LEFT OUTER JOIN  CUSTOMER_STG.SUPPLIER_DETAIL SUPPLIER
ON PRODUCT.SUPPLIER_ID=SUPPLIER.SUPPLIER_ID;


---TABLE-5  CUSTOMER_INVOICE_ITEM_DTLS

DROP TABLE  IF  EXISTS CUSTOMER_CORE.CUSTOMER_INVOICE_ITEM_DTLS;

CREATE TABLE  IF NOT EXISTS CUSTOMER_CORE.CUSTOMER_INVOICE_ITEM_DTLS (
CUSTOMER_ID INT,CUSTOMER_FIRST_NAME STRING,
PRODUCT_TITLE STRING, PRODUCT_QTY VARCHAR(8) ,DERIVED_PRD_COST FLOAT, DERIVED_VAT_PYBL FLOAT ,DERIVED_TOT_COST FLOAT,
START_DATE DATE, END_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS ORC;

INSERT OVERWRITE TABLE CUSTOMER_CORE.CUSTOMER_INVOICE_ITEM_DTLS  
SELECT  CUSTOMER.CUSTOMER_ID ,CUSTOMER.CUSTOMER_FIRST_NAME ,
INVOICE_ITEM.PRODUCT_TITLE,INVOICE_ITEM.PRODUCT_QTY,INVOICE_ITEM.DERIVED_PRD_COST,INVOICE_ITEM.DERIVED_VAT_PYBL,INVOICE_ITEM.DERIVED_TOT_COST,
CUSTOMER.START_DATE ,CUSTOMER.END_DATE 
FROM CUSTOMER_STG.CUSTOMER CUSTOMER
INNER JOIN CUSTOMER_STG.DELIVERY_DETAIL DELIVERY
ON CUSTOMER.CUSTOMER_ID=DELIVERY.CUSTOMER_ID
LEFT OUTER JOIN  CUSTOMER_STG.PRODUCT PRODUCT
ON DELIVERY.PRODUCT_ID=PRODUCT.PRODUCT_ID
LEFT OUTER JOIN CUSTOMER_STG.INVOICE_LINE_ITEMS INVOICE_ITEM
ON PRODUCT.PRODUCT_ID=INVOICE_ITEM.PRODUCT_ID;

---TABLE-6  SUPPLIER_SHIPPING_DTLS

DROP TABLE  IF  EXISTS CUSTOMER_CORE.SUPPLIER_SHIPPING_DTLS;

CREATE TABLE  IF NOT EXISTS CUSTOMER_CORE.SUPPLIER_SHIPPING_DTLS (
SUPPLIER_ID INT,SUPPLIED_ITEMS STRING,SUPPLIER_STATUS CHAR(1),
MODE_OF_SHIPPING STRING, COURIER_NM STRING,
START_DATE DATE, END_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS ORC;

INSERT OVERWRITE TABLE CUSTOMER_CORE.SUPPLIER_SHIPPING_DTLS  
SELECT  SUPPLIER.SUPPLIER_ID, SUPPLIER.SUPPLIED_ITEMS,SUPPLIER.SUPPLIER_STATUS,
 SHIPPING.MODE_OF_SHIPPING,SHIPPING.COURIER_NM ,
SUPPLIER.START_DATE ,SUPPLIER.END_DATE 
FROM CUSTOMER_STG.SUPPLIER_DETAIL SUPPLIER
LEFT OUTER JOIN  CUSTOMER_STG.PRODUCT PRODUCT
ON SUPPLIER.SUPPLIER_ID=PRODUCT.SUPPLIER_ID
INNER JOIN CUSTOMER_STG.DELIVERY_DETAIL DELIVERY
ON PRODUCT.PRODUCT_ID=DELIVERY.PRODUCT_ID
LEFT OUTER JOIN CUSTOMER_STG.SHIPPING_DETAIL SHIPPING
ON SHIPPING.DELIVER_ID=DELIVERY.DELIVER_ID ;

---TABLE-7  SUPPLIER_PROD_TYP_DTLS

DROP TABLE  IF  EXISTS CUSTOMER_CORE.SUPPLIER_PROD_TYP_DTLS;

CREATE TABLE  IF NOT EXISTS CUSTOMER_CORE.SUPPLIER_PROD_TYP_DTLS (
SUPPLIER_ID INT,SUPPLIED_ITEMS STRING,SUPPLIER_STATUS CHAR(1),
PRODUCT_TYPE_CD CHAR(4) ,PARENT_PRD_TYP_CD CHAR(4)  ,PRD_TYP_DESC STRING ,VAT_RATING CHAR(1)  ,
START_DATE DATE, END_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS ORC;

INSERT OVERWRITE TABLE CUSTOMER_CORE.SUPPLIER_PROD_TYP_DTLS  
SELECT  SUPPLIER.SUPPLIER_ID, SUPPLIER.SUPPLIED_ITEMS,SUPPLIER.SUPPLIER_STATUS,
PRODUCT_TYPE.PRODUCT_TYPE_CD,PRODUCT_TYPE.PARENT_PRD_TYP_CD ,PRODUCT_TYPE.PRD_TYP_DESC ,PRODUCT_TYPE.VAT_RATING ,
SUPPLIER.START_DATE ,SUPPLIER.END_DATE 
FROM CUSTOMER_STG.SUPPLIER_DETAIL SUPPLIER
INNER JOIN   CUSTOMER_STG.PRODUCT PRODUCT
ON SUPPLIER.SUPPLIER_ID=PRODUCT.SUPPLIER_ID
INNER JOIN CUSTOMER_STG.PRODUCT_TYPE PRODUCT_TYPE
ON PRODUCT.PRODUCT_TYPE_CD=PRODUCT_TYPE.PRODUCT_TYPE_CD;


select distinct SUPPLIER_ID from supplier_prod_typ_dtls


