/*  
# Description: TWITTER LIVE STREAMING CORE LOAD BY USING FLUME
# Created by: NANDAKUMAR PANDIAN
# Created on: 19/12/2016
# Revision History :
# Latest Modification History on top

# DD/MM/YYYY Who(Network id) Version Modification Details
# 19/12/2016        NANDAKUMAR PANDIAN      01         TWITTER LIVE STREAMING CORE LOAD BY USING FLUME
*/


---TABLE 1  FLUME_CUSTOMER_STUDENT_CORE

DROP TABLE  IF  EXISTS FLUME_CORE.FLUME_CUSTOMER_STUDENT_CORE;

CREATE TABLE  IF NOT EXISTS FLUME_CORE.FLUME_CUSTOMER_STUDENT_CORE (
ID BIGINT, CREATED_AT STRING, SOURCE STRING, FAVORITED BOOLEAN, RETWEETED_STATUS STRUCT<   TEXT:STRING,  USER:STRUCT<SCREEN_NAME:STRING,NAME:STRING>,  RETWEET_COUNT:INT>,
ENTITIES STRUCT< URLS:ARRAY<STRUCT<EXPANDED_URL:STRING>>,USER_MENTIONS:ARRAY<STRUCT<SCREEN_NAME:STRING,NAME:STRING>>,HASHTAGS:ARRAY<STRUCT<TEXT:STRING>>>,
TEXT STRING,  USER STRUCT<  SCREEN_NAME:STRING, NAME:STRING, FRIENDS_COUNT:INT, FOLLOWERS_COUNT:INT,STATUSES_COUNT:INT,VERIFIED:BOOLEAN,UTC_OFFSET:INT, TIME_ZONE:STRING>,
IN_REPLY_TO_SCREEN_NAME STRING)
ROW FORMAT SERDE 'com.cloudera.hive.serde.JSONSerDe'
LOCATION '/user/Flume/twitter_data/backup';

