/*  
# Description: STUDENT_ASSESSMENT CORE TABLES LOAD
# Created by: NANDAKUMAR PANDIAN
# Created on: 19/12/2016
# Revision History :
# Latest Modification History on top
# DD/MM/YYYY Who(Network id) Version Modification Details
# 19/12/2016        NANDAKUMAR PANDIAN      01         STUDENT_ASSESSMENT CORE TABLES LOAD
*/

------Customer Core Table coding
SET hive.exec.dynamic.partition.mode=nonstrict;

---TABLE-1  STUDENT_ASS_STUDENT_DTLS

DROP TABLE  IF  EXISTS STUDENT_CORE.STUDENT_ASS_STUDENT_DTLS;

CREATE TABLE  IF NOT EXISTS STUDENT_CORE.STUDENT_ASS_STUDENT_DTLS (
STUDENT_ID INT,ASSESSMENT_ID INT,ADDRESS_ID INT ,
FIRST_NAME STRING,MIDDLE_NAME STRING,LAST_NAME STRING,CELL_MOBILE_NUMBER BIGINT,EMAIL_ADDRESS STRING,DATE_FIRST_RENTA DATE ,DATE_LEFT_UNIVERSITY DATE,
ASSMNT_SUMMARY STRING ,ASSMNT_SCORE STRING ,
START_DATE DATE, END_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS ORC;

INSERT OVERWRITE TABLE STUDENT_CORE.STUDENT_ASS_STUDENT_DTLS  
SELECT  STUDENT_ASSESSMENT.STUDENT_ID ,STUDENT_ASSESSMENT.ASSESSMENT_ID ,
STUDENT.ADDRESS_ID,STUDENT.FIRST_NAME,STUDENT.MIDDLE_NAME,STUDENT.LAST_NAME,STUDENT.CELL_MOBILE_NUMBER,STUDENT.EMAIL_ADDRESS,STUDENT.DATE_FIRST_RENTAL,STUDENT.DATE_LEFT_UNIVERSITY,
ASSESSMENTS.ASSMNT_SUMMARY,ASSESSMENTS.ASSMNT_SCORE,
STUDENT_ASSESSMENT.START_DATE ,STUDENT_ASSESSMENT.END_DATE 
FROM STUDENT_STG.STUDENT_ASSESSMENT STUDENT_ASSESSMENT
INNER JOIN STUDENT_STG.STUDENT STUDENT
ON STUDENT_ASSESSMENT.STUDENT_ID=STUDENT.STUDENT_ID
LEFT OUTER JOIN  STUDENT_STG.ASSESSMENTS ASSESSMENTS
ON STUDENT_ASSESSMENT.ASSESSMENT_ID=ASSESSMENTS.ASSESSMENT_ID;

---TABLE 2  STUDENT_ACH_CMTS_DTLS

DROP TABLE  IF  EXISTS STUDENT_CORE.STUDENT_ACH_CMTS_DTLS;

CREATE TABLE  IF NOT EXISTS STUDENT_CORE.STUDENT_ACH_CMTS_DTLS (
STUDENT_ID INT,ASSESSMENT_ID INT,ADDRESS_ID INT ,
ACHIVE_TYP_CD CHAR(4)   ,DATE_ACHIVE DATE ,ACHIVE_DTLS STRING ,COMMENT_CD  CHAR(4),
START_DATE DATE, END_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS ORC;

INSERT OVERWRITE TABLE STUDENT_CORE.STUDENT_ACH_CMTS_DTLS  
SELECT  STUDENT_ASS_STUDENT_DTLS.STUDENT_ID ,STUDENT_ASS_STUDENT_DTLS.ASSESSMENT_ID ,STUDENT_ASS_STUDENT_DTLS.ADDRESS_ID,
ACHIEVEMENT.ACHIVE_TYP_CD ,ACHIEVEMENT.DATE_ACHIVE,ACHIEVEMENT.ACHIVE_DTLS ,ACHIEVEMENT_COMMENTS.COMMENT_CD,
STUDENT_ASS_STUDENT_DTLS.START_DATE ,STUDENT_ASS_STUDENT_DTLS.END_DATE 
FROM STUDENT_CORE.STUDENT_ASS_STUDENT_DTLS   STUDENT_ASS_STUDENT_DTLS
INNER JOIN STUDENT_STG.ACHIEVEMENT ACHIEVEMENT
ON STUDENT_ASS_STUDENT_DTLS.STUDENT_ID=ACHIEVEMENT.STUDENT_ID
LEFT OUTER JOIN  STUDENT_STG.ACHIEVEMENT_COMMENTS ACHIEVEMENT_COMMENTS
ON STUDENT_ASS_STUDENT_DTLS.ASSESSMENT_ID=ACHIEVEMENT_COMMENTS.ASSESSMENT_ID;

---TABLE 3  STUDENT_STAFF_ROLE_DTLS

DROP TABLE  IF  EXISTS STUDENT_CORE.STUDENT_STAFF_ROLE_DTLS;

CREATE TABLE  IF NOT EXISTS STUDENT_CORE.STUDENT_STAFF_ROLE_DTLS (
STUDENT_ID INT,ASSESSMENT_ID INT,ADDRESS_ID INT ,
STAFF_ID INT ,DEPARTMENT_CD CHAR(4),DEPARTMENT_DESCRIPTION STRING,
START_DATE DATE, END_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS ORC;

INSERT OVERWRITE TABLE STUDENT_CORE.STUDENT_STAFF_ROLE_DTLS  
SELECT  STUDENT_ASS_STUDENT_DTLS.STUDENT_ID ,STUDENT_ASS_STUDENT_DTLS.ASSESSMENT_ID ,STUDENT_ASS_STUDENT_DTLS.ADDRESS_ID,
STAFF.STAFF_ID,STAFF.DEPARTMENT_CD,STAFF_ROLES.DEPARTMENT_DESCRIPTION,
STUDENT_ASS_STUDENT_DTLS.START_DATE ,STUDENT_ASS_STUDENT_DTLS.END_DATE 
FROM STUDENT_CORE.STUDENT_ASS_STUDENT_DTLS   STUDENT_ASS_STUDENT_DTLS
INNER JOIN STUDENT_STG.ASSESSMENT_NOTES ASSESSMENT_NOTES
ON STUDENT_ASS_STUDENT_DTLS.ASSESSMENT_ID=ASSESSMENT_NOTES.ASSESSMENT_ID
LEFT OUTER JOIN  STUDENT_STG.STAFF STAFF
ON ASSESSMENT_NOTES.STAFF_ID=STAFF.STAFF_ID
LEFT OUTER JOIN  STUDENT_STG.STAFF_ROLES STAFF_ROLES
ON STAFF.DEPARTMENT_CD=STAFF_ROLES.DEPARTMENT_CODE;

---TABLE 4  STUDENT_ADDRESS_DTLS

DROP TABLE  IF  EXISTS STUDENT_CORE.STUDENT_ADDRESS_DTLS;

CREATE TABLE  IF NOT EXISTS STUDENT_CORE.STUDENT_ADDRESS_DTLS (
STUDENT_ID INT,ASSESSMENT_ID INT,ADDRESS_ID INT ,
LINE_1 STRING,LINE_2 STRING,LINE_3 STRING,STATE STRING ,COUNTRY STRING,
START_DATE DATE, END_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS ORC;

INSERT OVERWRITE TABLE STUDENT_CORE.STUDENT_ADDRESS_DTLS  
SELECT  STUDENT_ASS_STUDENT_DTLS.STUDENT_ID ,STUDENT_ASS_STUDENT_DTLS.ASSESSMENT_ID ,STUDENT_ASS_STUDENT_DTLS.ADDRESS_ID,
ADDRESS.LINE_1,ADDRESS.LINE_2,ADDRESS.LINE_3,ADDRESS.STATE,ADDRESS.COUNTRY,
STUDENT_ASS_STUDENT_DTLS.START_DATE ,STUDENT_ASS_STUDENT_DTLS.END_DATE 
FROM STUDENT_CORE.STUDENT_ASS_STUDENT_DTLS   STUDENT_ASS_STUDENT_DTLS
INNER JOIN STUDENT_STG.ADDRESS ADDRESS
ON STUDENT_ASS_STUDENT_DTLS.ASSESSMENT_ID=ADDRESS.ASSESSMENT_ID;



